on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        container: node

        steps:
            - uses: actions/checkout@v3

            - name: Install npm modules
              run: npm install

            - name: Run build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-data
                  path: dist
