on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        container: node
        defaults:
            run:
                working-directory: ./client

        steps:
            - uses: actions/checkout@v3

            - name: Install npm modules
              run: npm install

            - name: Run build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-data
                  path: client/build

    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./client

        steps:
            - name: Download build data
              uses: actions/download-artifact@v3
              with:
                  name: build-data
                  path: client/build

            - name: Push build data (Deploy)
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: jp.lann.ru
                  port: 22752
                  username: japan
                  overwrite: true
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: "build/*"
                  target: /home/japan/www/client
